tasks:
  - name: Backend
    before: cd back
    command: |
      npm install 
      npm start
  - name: Frontend
    before: cd front 
    command: |
      python -m http.server 5500
ports:
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 5500
    onOpen: open-preview
    visibility: public